// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ConsoleApp1.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp1.Models
{
    public partial interface ITestContextProcedures
    {
        Task<List<SpsEmployeeHistoryResult>> SpsEmployeeHistoryAsync(DateTime? startDate, DateTime? EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
