SELECT TABLE_SCHEMA, TABLE_NAME, COLLATION_NAME
FROM   INFORMATION_SCHEMA.COLUMNS			
WHERE  DATA_TYPE='geography'

SELECT TABLE_SCHEMA, TABLE_NAME, COLLATION_NAME
			FROM   INFORMATION_SCHEMA.COLUMNS			
			WHERE  DATA_TYPE='geometry'
