// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCoreWithPostgreSQL.WebAPI.Models;

public partial class Employee
{
    public Guid EmployeeId { get; set; }

    public string Name { get; set; }

    public string Position { get; set; }

    public string Department { get; set; }

    public string Address { get; set; }

    public decimal AnnualSalary { get; set; }
}