// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SQL_Server_In_Memory_DB.Models;

public partial class Test1
{
    public int Id { get; set; }

    public string Value { get; set; }
}