SELECT TOP (1000) [EmployeeID]
      ,[Name]
      ,[Position]
      ,[Department]
      ,[Address]
      ,[AnnualSalary]
      ,[ValidFrom]
      ,[ValidTo]
  FROM [Test].[dbo].[Employee]

SELECT TOP (1000) [EmployeeID]
      ,[Name]
      ,[Position]
      ,[Department]
      ,[Address]
      ,[AnnualSalary]
      ,[ValidFrom]
      ,[ValidTo]
  FROM [Test].[dbo].[EmployeeHistory]
